version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test_db
    ports:
      - 3306:3306
    volumes:
      - ./database/sql:/docker-entrypoint-initdb.d